name: Sync Calendar

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download calendar
        run: |
          curl -L "https://app.mymusicstaff.com/ical/teacher/qoKLnlTWJvgjeZr3Rm1%2BN1OkhFyp8JlGhW1gy3MxIkg%3D.ics" -o calendar.ics

      - name: Commit changes
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "bot@example.com"
          git add calendar.ics
          git commit -m "update calendar" || echo "no changes"
          git push
