name: Sync Calendar

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download calendar
        run: |
          run: |
  curl -L \
       --fail \
       --compressed \
       -H "Accept: text/calendar" \
       -H "User-Agent: AppleCoreMedia/1.0.0.21E230 (iPhone; U; CPU OS 17_0 like Mac OS X)" \
       "https://app.mymusicstaff.com/CalendarFeed.ashx?User=tch_mS8J2.qoKLnlTWJvgjeZr3Rm1%2BN1OkhFyp8JlGhW1gy3MxIkg%3D" \
       -o calendar.ics

      - name: Commit changes
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "bot@example.com"
          git add calendar.ics
          git commit -m "update calendar" || echo "no changes"
          git push
